require_relative 'seed_globals'
#############################################################################
# Keys
#   This Section represents the physical keys as they appear on the keyboard
#   The data here will be used to display the keys, and also save what
#   keycodes are mapped to them. The x_pos and y_pos are used to position
#   the keys on the keyboard, relative to the keyblock it's attached to.
#   I chose to add the keys in blocks because it reduces the amount of
#   maths i had to do in my head to make all the keys align properly.
#   A standard key has a width and height of 10 * sf (Scale Factor)
#############################################################################
# MX Keys
Key.create({name: 'MX1' , scancode: '700e8', keygroup_id: $kg[:left].id, keycode1: $kc[:k179].id, x_pos: 0 * $sf , y_pos: 0*$sf , keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX2' , scancode: '700e9', keygroup_id: $kg[:left].id, keycode1: $kc[:k180].id, x_pos: 10*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX3' , scancode: '700ea', keygroup_id: $kg[:left].id, keycode1: $kc[:k181].id, x_pos: 0*$sf   , y_pos: 10*$sf, keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX4' , scancode: '700eb', keygroup_id: $kg[:left].id, keycode1: $kc[:k182].id, x_pos: 10*$sf  , y_pos: 10*$sf, keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX5' , scancode: '700ec', keygroup_id: $kg[:left].id, keycode1: $kc[:k183].id, x_pos: 0*$sf   , y_pos: 20*$sf, keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX6' , scancode: '700ed', keygroup_id: $kg[:left].id, keycode1: $kc[:k184].id, x_pos: 10*$sf  , y_pos: 20*$sf, keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX7' , scancode: '700ee', keygroup_id: $kg[:left].id, keycode1: $kc[:k185].id, x_pos: 0*$sf   , y_pos: 30*$sf, keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX8' , scancode: '700ef', keygroup_id: $kg[:left].id, keycode1: $kc[:k186].id, x_pos: 10*$sf  , y_pos: 30*$sf, keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX9' , scancode: '700f0', keygroup_id: $kg[:left].id, keycode1: $kc[:k187].id, x_pos: 0*$sf   , y_pos: 40*$sf, keyblock_id: $kb[:MXKeys].id})
Key.create({name: 'MX10', scancode: '700f1', keygroup_id: $kg[:left].id, keycode1: $kc[:k188].id, x_pos: 10*$sf  , y_pos: 40*$sf, keyblock_id: $kb[:MXKeys].id})
# M Keys
Key.create({name: 'M1'  , scancode: '700f4', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 0*$sf    , y_pos: 0*$sf , keyblock_id: $kb[:MKeys1].id})
Key.create({name: 'M2'  , scancode: '700f5', keygroup_id: $kg[:top].id, keycode1: $kc[:k190].id, x_pos: 10*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys1].id})
Key.create({name: 'M3'  , scancode: '700f6', keygroup_id: $kg[:top].id, keycode1: $kc[:k191].id, x_pos: 20*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys1].id})
Key.create({name: 'M4'  , scancode: '700f7', keygroup_id: $kg[:top].id, keycode1: $kc[:k192].id, x_pos: 30*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys1].id})
Key.create({name: 'M5'  , scancode: '700f8', keygroup_id: $kg[:top].id, keycode1: $kc[:k193].id, x_pos: 0*$sf    , y_pos: 0*$sf , keyblock_id: $kb[:MKeys2].id})
Key.create({name: 'M6'  , scancode: '700f9', keygroup_id: $kg[:top].id, keycode1: $kc[:k194].id, x_pos: 10*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys2].id})
Key.create({name: 'M7'  , scancode: '700fa', keygroup_id: $kg[:top].id, keycode1: $kc[:k195].id, x_pos: 20*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys2].id})
Key.create({name: 'M8'  , scancode: '700fb', keygroup_id: $kg[:top].id, keycode1: $kc[:k196].id, x_pos: 30*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys2].id})
Key.create({name: 'M9'  , scancode: '700fc', keygroup_id: $kg[:top].id, keycode1: $kc[:k197].id, x_pos: 0*$sf    , y_pos: 0*$sf , keyblock_id: $kb[:MKeys3].id})
Key.create({name: 'M10' , scancode: '700fd', keygroup_id: $kg[:top].id, keycode1: $kc[:k198].id, x_pos: 10*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys3].id})
Key.create({name: 'M11' , scancode: '700fe', keygroup_id: $kg[:top].id, keycode1: $kc[:k199].id, x_pos: 20*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys3].id})
Key.create({name: 'M12' , scancode: '700ff', keygroup_id: $kg[:top].id, keycode1: $kc[:k200].id, x_pos: 30*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:MKeys3].id})
# L Keys
Key.create({name: 'L1', scancode: '700a8', keygroup_id: $kg[:left].id, keycode1: $kc[:k201].id, x_pos: 0*$sf     , y_pos: 0*$sf , keyblock_id: $kb[:LKeys].id})
Key.create({name: 'L2', scancode: '700a9', keygroup_id: $kg[:left].id, keycode1: $kc[:k202].id, x_pos: 10*$sf    , y_pos: 0*$sf , keyblock_id: $kb[:LKeys].id})
Key.create({name: 'L3', scancode: '700aa', keygroup_id: $kg[:left].id, keycode1: $kc[:k203].id, x_pos: 0*$sf     , y_pos: 10*$sf, keyblock_id: $kb[:LKeys].id})
Key.create({name: 'L4', scancode: '700ab', keygroup_id: $kg[:left].id, keycode1: $kc[:k204].id, x_pos: 10*$sf    , y_pos: 10*$sf, keyblock_id: $kb[:LKeys].id})
# Sound Keys
Key.create({name: 'V+'  , scancode: 'c00e9' , keygroup_id: $kg[:right].id, keycode1: $kc[:k123].id, x_pos: 0*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:MediaKeys1].id})
Key.create({name: 'V-'  , scancode: 'c00e9' , keygroup_id: $kg[:right].id, keycode1: $kc[:k123].id, x_pos: 0*$sf  , y_pos: 10*$sf , keyblock_id: $kb[:MediaKeys1].id})
Key.create({name: 'Mute', scancode: 'c00e2' , keygroup_id: $kg[:right].id, keycode1: $kc[:k123].id, x_pos: 0*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:MediaKeys2].id})
Key.create({name: 'Prev', scancode: 'c00b6' , keygroup_id: $kg[:right].id, keycode1: $kc[:k123].id, x_pos: 0*$sf  , y_pos: 10*$sf , keyblock_id: $kb[:MediaKeys2].id})
Key.create({name: 'Next', scancode: 'c00b5' , keygroup_id: $kg[:right].id, keycode1: $kc[:k123].id, x_pos: 0*$sf  , y_pos: 20*$sf , keyblock_id: $kb[:MediaKeys2].id})
Key.create({name:'Play Pause', scancode: 'c00cd' , keygroup_id: $kg[:right].id, keycode1: $kc[:k123].id, x_pos: 0*$sf  , y_pos: 30*$sf , keyblock_id: $kb[:MediaKeys2].id,eclass:'Play'})
# Regular Keys
Key.create({name: 'Esc', scancode: '00000', keygroup_id: $kg[:top].id   , keycode1: $kc[:k999], x_pos: 0*$sf   , y_pos: 0*$sf  , keyblock_id: $kb[:Esc].id,eclass:'Escape'})
# Qwerty Numbers
Key.create({name: '~'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 0*$sf   , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '1'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 10*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '2'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 20*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '3'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 30*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '4'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 40*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '5'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 50*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '6'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 60*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '7'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 70*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '8'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 80*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '9'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 90*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '0'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 100*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '-'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 110*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name: '='     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 120*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id})
Key.create({name:'Backspace',scancode:'00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 130*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyNo].id,eclass: 'Backspace'})
# Qwerty Line 1
Key.create({name:'Tab'    , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 0*$sf   , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id,eclass: 'Tab'})
Key.create({name:'Q'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 15*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'W'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 25*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'E'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 35*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'R'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 45*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'T'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 55*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'Y'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 65*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'U'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 75*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'I'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 85*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'O'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 95*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'P'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 105*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'['      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 115*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:']'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 125*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL1].id})
Key.create({name:'\\'     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 135*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL1].id,eclass: 'BSlash'})
# Qwerty Line 2
Key.create({name:'Caps'   , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 0*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id,eclass: 'Caps'})
Key.create({name:'A'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 18*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'S'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 28*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'D'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 38*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'F'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 48*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'G'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 58*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'H'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 68*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'J'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 78*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'K'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 88*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'L'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 98*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:';'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 108*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'\''     , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 118*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id})
Key.create({name:'Rtn'    , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 128*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL2].id,eclass: 'Return'})
# Qwerty Line 3
Key.create({name:'LShft'  , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 0*$sf   , y_pos: 0*$sf ,   keyblock_id: $kb[:QwertyL3].id,eclass: 'LShift'})
Key.create({name:'Z'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 22*$sf  , y_pos: 0*$sf ,  keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'X'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 32*$sf  , y_pos: 0*$sf ,  keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'C'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 42*$sf  , y_pos: 0*$sf ,  keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'V'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 52*$sf  , y_pos: 0*$sf ,  keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'B'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 62*$sf  , y_pos: 0*$sf ,  keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'N'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 72*$sf  , y_pos: 0*$sf ,  keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'M'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 82*$sf  , y_pos: 0*$sf ,  keyblock_id: $kb[:QwertyL3].id})
Key.create({name:','      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 92*$sf  , y_pos: 0*$sf ,  keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'.'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 102*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'/'      , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 112*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL3].id})
Key.create({name:'RShft'  , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 122*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyL3].id,eclass: 'RShift'})
# Qwerty Functions
Key.create({name:'LCtrl'  , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 0*$sf   , y_pos: 0*$sf , keyblock_id: $kb[:QwertyFunc].id,eclass: 'Ctrl'})
Key.create({name:'Win'    , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 13*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyFunc].id,eclass: 'Win'})
Key.create({name:'LAlt'   , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 28*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyFunc].id,eclass: 'Alt'})
Key.create({name:'Space'  , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 43*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyFunc].id,eclass: 'Space'})
Key.create({name:'RAlt'   , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 97*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:QwertyFunc].id,eclass: 'Alt'})
Key.create({name:'Apex'   , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 112*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyFunc].id,eclass: 'Apex'})
Key.create({name:'List'   , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 127*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyFunc].id,eclass: 'ListKey'})
Key.create({name:'RCtrl'  , scancode: '00000', keygroup_id: $kg[:bottom].id, keycode1: $kc[:k999], x_pos: 137*$sf , y_pos: 0*$sf , keyblock_id: $kb[:QwertyFunc].id,eclass: 'Ctrl'})
# PrnScn Area
Key.create({name:'PRT SCN'   , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 0*$sf  , y_pos: 0*$sf , keyblock_id: $kb[:PrtScr].id,eclass:'TwoLine'})
Key.create({name:'SCRL LOCK' , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos: 0*$sf , keyblock_id: $kb[:PrtScr].id,eclass:'TwoLine'})
Key.create({name:'PAUSE'     , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 0*$sf , keyblock_id: $kb[:PrtScr].id})
# NumPad
Key.create({name:'NUM LOCK'  , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 0*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:NumPad].id,eclass:'TwoLine'})
Key.create({name:'/'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:NumPad].id})
Key.create({name:'*'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:NumPad].id})
Key.create({name:'-'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 30*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:NumPad].id})
Key.create({name:'7'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 00*$sf , y_pos: 10*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'8'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos: 10*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'9'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 10*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'+'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 30*$sf , y_pos: 10*$sf , keyblock_id: $kb[:NumPad].id,eclass:'NumPlus'})
Key.create({name:'4'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 00*$sf , y_pos: 20*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'5'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos: 20*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'6'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 20*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'1'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 00*$sf , y_pos: 30*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'2'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos: 30*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'3'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 30*$sf , keyblock_id: $kb[:NumPad].id})
Key.create({name:'Enter'     , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 30*$sf , y_pos: 30*$sf , keyblock_id: $kb[:NumPad].id,eclass:'NumEnter'})
Key.create({name:'0'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 00*$sf , y_pos: 40*$sf , keyblock_id: $kb[:NumPad].id,eclass:'Num0'})
Key.create({name:'.'         , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 40*$sf , keyblock_id: $kb[:NumPad].id})
# Ins Area
Key.create({name:'INS'       , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 0*$sf  , y_pos: 0*$sf  , keyblock_id: $kb[:Ins].id})
Key.create({name:'HOME'      , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:Ins].id})
Key.create({name:'PG UP'     , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 0*$sf  , keyblock_id: $kb[:Ins].id})
Key.create({name:'DEL'       , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 00*$sf , y_pos: 10*$sf , keyblock_id: $kb[:Ins].id})
Key.create({name:'END'       , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos: 10*$sf , keyblock_id: $kb[:Ins].id})
Key.create({name:'PG DN'     , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 10*$sf , keyblock_id: $kb[:Ins].id})
# Arrows
Key.create({name:'UP LEFT'   , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 0*$sf  , y_pos:  0*$sf , keyblock_id: $kb[:Arrows].id,eclass:'TwoLine'})
Key.create({name:'UP'        , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos:  0*$sf , keyblock_id: $kb[:Arrows].id})
Key.create({name:'UP RIGHT'  , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos:  0*$sf , keyblock_id: $kb[:Arrows].id,eclass:'TwoLine'})
Key.create({name:'LEFT'      , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos:  0*$sf , y_pos: 10*$sf , keyblock_id: $kb[:Arrows].id})
Key.create({name:'DOWN'      , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 10*$sf , y_pos: 10*$sf , keyblock_id: $kb[:Arrows].id})
Key.create({name:'RIGHT'     , scancode: '00000', keygroup_id: $kg[:right].id, keycode1: $kc[:k999], x_pos: 20*$sf , y_pos: 10*$sf , keyblock_id: $kb[:Arrows].id})
# Function Keys

Key.create({name: 'F1'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 0*$sf      , y_pos: 10*$sf , keyblock_id: $kb[:MKeys1].id})
Key.create({name: 'F2'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 10*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys1].id})
Key.create({name: 'F3'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 20*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys1].id})
Key.create({name: 'F4'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 30*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys1].id})

Key.create({name: 'F5'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 0*$sf      , y_pos: 10*$sf , keyblock_id: $kb[:MKeys2].id})
Key.create({name: 'F6'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 10*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys2].id})
Key.create({name: 'F7'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 20*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys2].id})
Key.create({name: 'F8'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 30*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys2].id})

Key.create({name: 'F9'  , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 0*$sf      , y_pos: 10*$sf , keyblock_id: $kb[:MKeys3].id})
Key.create({name: 'F10' , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 10*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys3].id})
Key.create({name: 'F11' , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 20*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys3].id})
Key.create({name: 'F12' , scancode: '00000', keygroup_id: $kg[:top].id, keycode1: $kc[:k189].id, x_pos: 30*$sf     , y_pos: 10*$sf , keyblock_id: $kb[:MKeys3].id})